### ISSUE TITLE
java 里面的getBytes()用法怎么使用这个这个项目做相同的事情

### ISSUE THREAD

**Issue by liugang** [sineycoder/go-bigger#2]
```java
import java.math.BigInteger;
import java.util.Arrays;


public class Main {
    public static void main(String[] args) throws Exception {


        String str = "abc";
        byte []strBytes = str.getBytes();

        System.out.println(Arrays.toString(strBytes));

        BigInteger bi = new BigInteger(strBytes);
        System.out.println(bi);
    }



}
```

因为使用了getBytes(), 可以传递任何字符串.

javac Main.java 
java Main

```
[97, 98, 99]
6382179
```

而且 import java.math.BigInteger; 有xor这些方法, 该项目没有

**Comment by liugang** [comment]
我用golang自带的可以了,  我觉得这个项目也需要添加一个支持[]byte的api:    bigger.NewBigDecimalBytes([]byte("abc"))


```go
package main

import (
	"fmt"
	"math/big"
)

func main() {
	i := new(big.Int)

	bytes := []byte("abc")
	fmt.Println(bytes)
	i.SetBytes(bytes)

	fmt.Println(i)
}

```

go run main.go


```
[97 98 99]
6382179
```

**Comment by sineycoder** [comment]
> ```java
> import java.math.BigInteger;
> import java.util.Arrays;
> 
> 
> public class Main {
>     public static void main(String[] args) throws Exception {
> 
> 
>         String str = "abc";
>         byte []strBytes = str.getBytes();
> 
>         System.out.println(Arrays.toString(strBytes));
> 
>         BigInteger bi = new BigInteger(strBytes);
>         System.out.println(bi);
>     }
> 
> 
> 
> }
> ```
> 
> 因为使用了getBytes(), 可以传递任何字符串.
> 
> javac Main.java java Main
> 
> ```
> [97, 98, 99]
> 6382179
> ```
> 
> 而且 import java.math.BigInteger; 有xor这些方法, 该项目没有

谢谢你的提议，我后续会补充并加上。一开始写这个是为了解决当前问题，有部分方法没有实现。
